version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: combinations
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: 'yes'
      command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

